// Mocks generated by Mockito 5.4.5 from annotations
// in flowery/test/features/categories/data/data_source/categories_screen_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;
import 'dart:io' as _i22;

import 'package:flowery/core/api_manger/api_service.dart' as _i16;
import 'package:flowery/core/utils/models/products_model/products_model.dart'
    as _i4;
import 'package:flowery/features/address/data/models/add_address_response/add_address_response.dart'
    as _i12;
import 'package:flowery/features/address/data/models/address_model.dart'
    as _i13;
import 'package:flowery/features/address/data/models/logged_user_address_model.dart'
    as _i11;
import 'package:flowery/features/address/data/models/user_address_data.dart'
    as _i23;
import 'package:flowery/features/auth/login/data/models/login_request.dart'
    as _i19;
import 'package:flowery/features/auth/login/data/models/login_respose.dart'
    as _i5;
import 'package:flowery/features/auth/register/data/models/register_request.dart'
    as _i18;
import 'package:flowery/features/auth/register/data/models/register_response.dart'
    as _i2;
import 'package:flowery/features/best_seller/data/models/best_seller_model.dart'
    as _i8;
import 'package:flowery/features/cart/data/models/add_product_request.dart'
    as _i20;
import 'package:flowery/features/cart/data/models/cart_model/cart_response.dart'
    as _i6;
import 'package:flowery/features/categories/data/models/categories_model/categories_model.dart'
    as _i3;
import 'package:flowery/features/check_out/data/models/cash_order_response.dart'
    as _i15;
import 'package:flowery/features/check_out/data/models/check_out_session_response.dart'
    as _i14;
import 'package:flowery/features/check_out/data/models/shipping_address_model.dart'
    as _i24;
import 'package:flowery/features/my_orders/data/models/orders/orders.dart'
    as _i25;
import 'package:flowery/features/occasion/data/models/occaions.dart' as _i7;
import 'package:flowery/features/productsDetails/data/models/product_details_model/product_details_model.dart'
    as _i9;
import 'package:flowery/features/profile/data/model/user_response.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesModel_1 extends _i1.SmartFake
    implements _i3.CategoriesModel {
  _FakeCategoriesModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsModel_2 extends _i1.SmartFake implements _i4.ProductsModel {
  _FakeProductsModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_3 extends _i1.SmartFake implements _i5.LoginResponse {
  _FakeLoginResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponse_4 extends _i1.SmartFake implements _i6.CartResponse {
  _FakeCartResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAllOccaions_5 extends _i1.SmartFake implements _i7.AllOccaions {
  _FakeAllOccaions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBestSellerModel_6 extends _i1.SmartFake
    implements _i8.BestSellerModel {
  _FakeBestSellerModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailsModel_7 extends _i1.SmartFake
    implements _i9.ProductDetailsModel {
  _FakeProductDetailsModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_8 extends _i1.SmartFake implements _i10.UserResponse {
  _FakeUserResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoggedUserAddressModel_9 extends _i1.SmartFake
    implements _i11.LoggedUserAddressModel {
  _FakeLoggedUserAddressModel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddAddressResponse_10 extends _i1.SmartFake
    implements _i12.AddAddressResponse {
  _FakeAddAddressResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressModel_11 extends _i1.SmartFake implements _i13.AddressModel {
  _FakeAddressModel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckoutSessionResponse_12 extends _i1.SmartFake
    implements _i14.CheckoutSessionResponse {
  _FakeCheckoutSessionResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCashOrderResponse_13 extends _i1.SmartFake
    implements _i15.CashOrderResponse {
  _FakeCashOrderResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i16.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i2.RegisterResponse> registerUser(
    _i18.RegisterRequest? registerRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [registerRequest]),
            returnValue: _i17.Future<_i2.RegisterResponse>.value(
              _FakeRegisterResponse_0(
                this,
                Invocation.method(#registerUser, [registerRequest]),
              ),
            ),
          )
          as _i17.Future<_i2.RegisterResponse>);

  @override
  _i17.Future<_i3.CategoriesModel> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i17.Future<_i3.CategoriesModel>.value(
              _FakeCategoriesModel_1(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i17.Future<_i3.CategoriesModel>);

  @override
  _i17.Future<_i4.ProductsModel> getProductsByCategory({
    String? categoryId,
    String? sort,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [], {
              #categoryId: categoryId,
              #sort: sort,
              #keyword: keyword,
            }),
            returnValue: _i17.Future<_i4.ProductsModel>.value(
              _FakeProductsModel_2(
                this,
                Invocation.method(#getProductsByCategory, [], {
                  #categoryId: categoryId,
                  #sort: sort,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i17.Future<_i4.ProductsModel>);

  @override
  _i17.Future<_i5.LoginResponse> loginUser(_i19.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [loginRequest]),
            returnValue: _i17.Future<_i5.LoginResponse>.value(
              _FakeLoginResponse_3(
                this,
                Invocation.method(#loginUser, [loginRequest]),
              ),
            ),
          )
          as _i17.Future<_i5.LoginResponse>);

  @override
  _i17.Future<_i6.CartResponse> addToCart(
    _i20.AddProductRequest? addProductRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [addProductRequest]),
            returnValue: _i17.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#addToCart, [addProductRequest]),
              ),
            ),
          )
          as _i17.Future<_i6.CartResponse>);

  @override
  _i17.Future<_i6.CartResponse> getUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, []),
            returnValue: _i17.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#getUserCart, [])),
            ),
          )
          as _i17.Future<_i6.CartResponse>);

  @override
  _i17.Future<_i6.CartResponse> deleteCartItem(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartItem, [cartItemId]),
            returnValue: _i17.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#deleteCartItem, [cartItemId]),
              ),
            ),
          )
          as _i17.Future<_i6.CartResponse>);

  @override
  _i17.Future<_i6.CartResponse> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i17.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#clearCart, [])),
            ),
          )
          as _i17.Future<_i6.CartResponse>);

  @override
  _i17.Future<_i6.CartResponse> updateCartProductQuantity(
    String? cartItemId,
    Map<String, dynamic>? productQuantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartProductQuantity, [
              cartItemId,
              productQuantity,
            ]),
            returnValue: _i17.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#updateCartProductQuantity, [
                  cartItemId,
                  productQuantity,
                ]),
              ),
            ),
          )
          as _i17.Future<_i6.CartResponse>);

  @override
  _i17.Future<_i7.AllOccaions> getAllOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOccasions, []),
            returnValue: _i17.Future<_i7.AllOccaions>.value(
              _FakeAllOccaions_5(this, Invocation.method(#getAllOccasions, [])),
            ),
          )
          as _i17.Future<_i7.AllOccaions>);

  @override
  _i17.Future<_i4.ProductsModel> getAllProductByOccasion({
    String? occasionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProductByOccasion, [], {
              #occasionId: occasionId,
            }),
            returnValue: _i17.Future<_i4.ProductsModel>.value(
              _FakeProductsModel_2(
                this,
                Invocation.method(#getAllProductByOccasion, [], {
                  #occasionId: occasionId,
                }),
              ),
            ),
          )
          as _i17.Future<_i4.ProductsModel>);

  @override
  _i17.Future<_i8.BestSellerModel> getBestSellerProduct() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSellerProduct, []),
            returnValue: _i17.Future<_i8.BestSellerModel>.value(
              _FakeBestSellerModel_6(
                this,
                Invocation.method(#getBestSellerProduct, []),
              ),
            ),
          )
          as _i17.Future<_i8.BestSellerModel>);

  @override
  _i17.Future<String> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i17.Future<String>.value(
              _i21.dummyValue<String>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<_i9.ProductDetailsModel> getProductDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [id]),
            returnValue: _i17.Future<_i9.ProductDetailsModel>.value(
              _FakeProductDetailsModel_7(
                this,
                Invocation.method(#getProductDetails, [id]),
              ),
            ),
          )
          as _i17.Future<_i9.ProductDetailsModel>);

  @override
  _i17.Future<_i10.UserResponse> editProfile(_i10.UpdatedUserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [user]),
            returnValue: _i17.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#editProfile, [user]),
              ),
            ),
          )
          as _i17.Future<_i10.UserResponse>);

  @override
  _i17.Future<_i10.UserResponse> getLoggedInUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedInUserData, []),
            returnValue: _i17.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#getLoggedInUserData, []),
              ),
            ),
          )
          as _i17.Future<_i10.UserResponse>);

  @override
  _i17.Future<String> uploadPhoto(_i22.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [image]),
            returnValue: _i17.Future<String>.value(
              _i21.dummyValue<String>(
                this,
                Invocation.method(#uploadPhoto, [image]),
              ),
            ),
          )
          as _i17.Future<String>);

  @override
  _i17.Future<_i11.LoggedUserAddressModel> getLoggedUserAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserAddress, []),
            returnValue: _i17.Future<_i11.LoggedUserAddressModel>.value(
              _FakeLoggedUserAddressModel_9(
                this,
                Invocation.method(#getLoggedUserAddress, []),
              ),
            ),
          )
          as _i17.Future<_i11.LoggedUserAddressModel>);

  @override
  _i17.Future<_i12.AddAddressResponse> updateAddress(
    _i23.UserAddressData? userAddress,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [userAddress, id]),
            returnValue: _i17.Future<_i12.AddAddressResponse>.value(
              _FakeAddAddressResponse_10(
                this,
                Invocation.method(#updateAddress, [userAddress, id]),
              ),
            ),
          )
          as _i17.Future<_i12.AddAddressResponse>);

  @override
  _i17.Future<_i12.AddAddressResponse> addNewAddress(
    _i23.UserAddressData? userAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewAddress, [userAddress]),
            returnValue: _i17.Future<_i12.AddAddressResponse>.value(
              _FakeAddAddressResponse_10(
                this,
                Invocation.method(#addNewAddress, [userAddress]),
              ),
            ),
          )
          as _i17.Future<_i12.AddAddressResponse>);

  @override
  _i17.Future<_i13.AddressModel> deleteAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [addressId]),
            returnValue: _i17.Future<_i13.AddressModel>.value(
              _FakeAddressModel_11(
                this,
                Invocation.method(#deleteAddress, [addressId]),
              ),
            ),
          )
          as _i17.Future<_i13.AddressModel>);

  @override
  _i17.Future<_i14.CheckoutSessionResponse> creditCheckOut(
    _i24.ShippingAddressModel? shippingAddressModel,
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#creditCheckOut, [shippingAddressModel, url]),
            returnValue: _i17.Future<_i14.CheckoutSessionResponse>.value(
              _FakeCheckoutSessionResponse_12(
                this,
                Invocation.method(#creditCheckOut, [shippingAddressModel, url]),
              ),
            ),
          )
          as _i17.Future<_i14.CheckoutSessionResponse>);

  @override
  _i17.Future<_i15.CashOrderResponse> cashCheckOut(
    _i24.ShippingAddressModel? shippingAddressModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cashCheckOut, [shippingAddressModel]),
            returnValue: _i17.Future<_i15.CashOrderResponse>.value(
              _FakeCashOrderResponse_13(
                this,
                Invocation.method(#cashCheckOut, [shippingAddressModel]),
              ),
            ),
          )
          as _i17.Future<_i15.CashOrderResponse>);

  @override
  _i17.Future<List<_i25.Orders>> getMyOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, []),
            returnValue: _i17.Future<List<_i25.Orders>>.value(<_i25.Orders>[]),
          )
          as _i17.Future<List<_i25.Orders>>);
}
