// Mocks generated by Mockito 5.4.5 from annotations
// in flowery/test/features/check_out/repo/check_out_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery/features/check_out/data/data_source/check_out_remote_data_source.dart'
    as _i4;
import 'package:flowery/features/check_out/data/models/cash_order_response.dart'
    as _i3;
import 'package:flowery/features/check_out/data/models/check_out_session_response.dart'
    as _i2;
import 'package:flowery/features/check_out/data/models/shipping_address_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCheckoutSessionResponse_0 extends _i1.SmartFake
    implements _i2.CheckoutSessionResponse {
  _FakeCheckoutSessionResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCashOrderResponse_1 extends _i1.SmartFake
    implements _i3.CashOrderResponse {
  _FakeCashOrderResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckOutRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOutRemoteDataSource extends _i1.Mock
    implements _i4.CheckOutRemoteDataSource {
  MockCheckOutRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CheckoutSessionResponse> creditCheckOut(
    _i6.ShippingAddressModel? shippingAddressModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#creditCheckOut, [shippingAddressModel]),
            returnValue: _i5.Future<_i2.CheckoutSessionResponse>.value(
              _FakeCheckoutSessionResponse_0(
                this,
                Invocation.method(#creditCheckOut, [shippingAddressModel]),
              ),
            ),
          )
          as _i5.Future<_i2.CheckoutSessionResponse>);

  @override
  _i5.Future<_i3.CashOrderResponse> cashCheckOut(
    _i6.ShippingAddressModel? shippingAddressModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cashCheckOut, [shippingAddressModel]),
            returnValue: _i5.Future<_i3.CashOrderResponse>.value(
              _FakeCashOrderResponse_1(
                this,
                Invocation.method(#cashCheckOut, [shippingAddressModel]),
              ),
            ),
          )
          as _i5.Future<_i3.CashOrderResponse>);
}
