// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6mT-c9u2S9dO660DUVQ_ZTcwEN9vevs',
    appId: '1:269852275314:web:86e2a9237ce6ec54e348eb',
    messagingSenderId: '269852275314',
    projectId: 'flower-app-b93d4',
    authDomain: 'flower-app-b93d4.firebaseapp.com',
    storageBucket: 'flower-app-b93d4.firebasestorage.app',
    measurementId: 'G-00FE5T49K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0KHUx8CgNEM3MRa1zVeC87sORVKH_TOw',
    appId: '1:269852275314:android:8d3fed1631d92e91e348eb',
    messagingSenderId: '269852275314',
    projectId: 'flower-app-b93d4',
    storageBucket: 'flower-app-b93d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9AECSOsxyE-XUkJIa56_d27IHrykN5s',
    appId: '1:269852275314:ios:a1beb87cba5e5447e348eb',
    messagingSenderId: '269852275314',
    projectId: 'flower-app-b93d4',
    storageBucket: 'flower-app-b93d4.firebasestorage.app',
    iosBundleId: 'com.example.flowery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu9AECSOsxyE-XUkJIa56_d27IHrykN5s',
    appId: '1:269852275314:ios:a1beb87cba5e5447e348eb',
    messagingSenderId: '269852275314',
    projectId: 'flower-app-b93d4',
    storageBucket: 'flower-app-b93d4.firebasestorage.app',
    iosBundleId: 'com.example.flowery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6mT-c9u2S9dO660DUVQ_ZTcwEN9vevs',
    appId: '1:269852275314:web:a474c8d8218ba563e348eb',
    messagingSenderId: '269852275314',
    projectId: 'flower-app-b93d4',
    authDomain: 'flower-app-b93d4.firebaseapp.com',
    storageBucket: 'flower-app-b93d4.firebasestorage.app',
    measurementId: 'G-3TGZXL21DS',
  );
}
