// Mocks generated by Mockito 5.4.5 from annotations
// in flowery/test/features/address/data/repos/repos/address_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/features/address/data/data_source/address_remote_data_source.dart'
    as _i3;
import 'package:flowery/features/address/data/models/add_address_response/add_address_response.dart'
    as _i2;
import 'package:flowery/features/address/data/models/address_model.dart' as _i7;
import 'package:flowery/features/address/data/models/logged_user_address_model.dart'
    as _i5;
import 'package:flowery/features/address/data/models/user_address_data.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddAddressResponse_0 extends _i1.SmartFake
    implements _i2.AddAddressResponse {
  _FakeAddAddressResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddressRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRemoteDataSource extends _i1.Mock
    implements _i3.AddressRemoteDataSource {
  MockAddressRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Addresses>?> getLoggedUserAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserAddress, []),
            returnValue: _i4.Future<List<_i5.Addresses>?>.value(),
          )
          as _i4.Future<List<_i5.Addresses>?>);

  @override
  _i4.Future<_i2.AddAddressResponse> addNewAddress(
    _i6.UserAddressData? userAddressData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewAddress, [userAddressData]),
            returnValue: _i4.Future<_i2.AddAddressResponse>.value(
              _FakeAddAddressResponse_0(
                this,
                Invocation.method(#addNewAddress, [userAddressData]),
              ),
            ),
          )
          as _i4.Future<_i2.AddAddressResponse>);

  @override
  _i4.Future<_i2.AddAddressResponse> updateAddress(
    _i6.UserAddressData? userAddressData,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [userAddressData, id]),
            returnValue: _i4.Future<_i2.AddAddressResponse>.value(
              _FakeAddAddressResponse_0(
                this,
                Invocation.method(#updateAddress, [userAddressData, id]),
              ),
            ),
          )
          as _i4.Future<_i2.AddAddressResponse>);

  @override
  _i4.Future<List<_i7.Address>?> deleteAddress({required String? addressId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {#addressId: addressId}),
            returnValue: _i4.Future<List<_i7.Address>?>.value(),
          )
          as _i4.Future<List<_i7.Address>?>);
}
