// Mocks generated by Mockito 5.4.5 from annotations
// in flowery/test/features/check_out/usecase/credit_check_out_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flowery/core/utils/error_handler.dart' as _i5;
import 'package:flowery/features/check_out/data/models/cash_order_response.dart'
    as _i6;
import 'package:flowery/features/check_out/data/models/check_out_session_response.dart'
    as _i8;
import 'package:flowery/features/check_out/data/models/shipping_address_model.dart'
    as _i7;
import 'package:flowery/features/check_out/domain/repos/check_out_repo.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckOutRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOutRepo extends _i1.Mock implements _i3.CheckOutRepo {
  MockCheckOutRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CashOrderResponse>> cashCheckOut(
    _i7.ShippingAddressModel? shippingAddressModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cashCheckOut, [shippingAddressModel]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, _i6.CashOrderResponse>
            >.value(
              _FakeEither_0<_i5.Failure, _i6.CashOrderResponse>(
                this,
                Invocation.method(#cashCheckOut, [shippingAddressModel]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CashOrderResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CheckoutSessionResponse>>
  creditCheckOut(_i7.ShippingAddressModel? shippingAddressModel) =>
      (super.noSuchMethod(
            Invocation.method(#creditCheckOut, [shippingAddressModel]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, _i8.CheckoutSessionResponse>
            >.value(
              _FakeEither_0<_i5.Failure, _i8.CheckoutSessionResponse>(
                this,
                Invocation.method(#creditCheckOut, [shippingAddressModel]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.CheckoutSessionResponse>>);
}
